// Copyright 2022 by Croquet Corporation. All Rights Reserved.
// Shared Dynaverse Constants
// Layers - there can be up to 32 different layers
// Events - pointer events are generated by the mouse, touch or XR control devices.

import { THREE } from "@croquet/worldcore";

export const D_CONSTANTS ={LIGHT_LAYER:1, EVENT_LAYER:2, WALK_LAYER:3, COLLIDE_LAYER:4, AVATAR_LAYER:5, 
    POINTER_DOWN: 1001, POINTER_UP: 1002, POINTER_MOVE:1003, POINTER_CANCEL:1004};